import { ALL_PRODUCTS_ENABLE_LOADING, CREATE_PRODUCT, CREATE_PRODUCT_ERROR, GET_ALL_PRODUCTS, GET_ALL_PRODUCTS_ERROR, PRODUCT_ENABLE_LOADING } from "../types/productTypes";
import { allItemsReducer, itemReducer } from "./utils/itemReducers";


export const allProductsReducer = allItemsReducer({ GET_ALL_ITEMS: GET_ALL_PRODUCTS, ALL_ITEMS_ENABLE_LOADING: ALL_PRODUCTS_ENABLE_LOADING, GET_ALL_ITEMS_ERROR: GET_ALL_PRODUCTS_ERROR });


export const productReducer = itemReducer({ CREATE_ITEM: CREATE_PRODUCT, ITEM_ENABLE_LOADING: PRODUCT_ENABLE_LOADING, CREATE_ITEM_ERROR: CREATE_PRODUCT_ERROR });
