import { ALL_SUB_CATEGORIES_ENABLE_LOADING, GET_ALL_SUB_CATEGORIES, GET_ALL_SUB_CATEGORIES_ERROR, CREATE_SUB_CATEGORY, CREATE_SUB_CATEGORY_ERROR, SUB_CATEGORY_ENABLE_LOADING } from "../types/subCategoryTypes";
import { allItemsReducer, itemReducer } from "./utils/itemReducers";


export const allSubCategoriesReducer = allItemsReducer({ GET_ALL_ITEMS: GET_ALL_SUB_CATEGORIES, ALL_ITEMS_ENABLE_LOADING: ALL_SUB_CATEGORIES_ENABLE_LOADING, GET_ALL_ITEMS_ERROR: GET_ALL_SUB_CATEGORIES_ERROR });


export const subCategoryReducer = itemReducer({ CREATE_ITEM: CREATE_SUB_CATEGORY, ITEM_ENABLE_LOADING: SUB_CATEGORY_ENABLE_LOADING, CREATE_ITEM_ERROR: CREATE_SUB_CATEGORY_ERROR });
