export const GET_ALL_BRANDS = "GET_ALL_BRANDS"

export const ALL_BRANDS_ENABLE_LOADING = "ALL_BRANDS_ENABLE_LOADING"

export const GET_ALL_BRANDS_ERROR = "GET_ALL_BRANDS_ERROR"

export const CREATE_BRAND = "CREATE_BRAND"

export const BRAND_ENABLE_LOADING = "BRAND_ENABLE_LOADING"

export const CREATE_BRAND_ERROR = "CREATE_BRAND_ERROR"