export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const CATEGORY_ENABLE_LOADING = "CATEGORY_ENABLE_LOADING";

export const CATEGORY_ERROR = "CATEGORY_ERROR";