export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"

export const ALL_CATEGORIES_ENABLE_LOADING = "ALL_CATEGORIES_ENABLE_LOADING"

export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR"

export const CREATE_CATEGORY = "CREATE_CATEGORY"

export const CATEGORY_ENABLE_LOADING = "CATEGORY_ENABLE_LOADING"

export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR"