export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_PRODUCT = "GET_PRODUCT";

export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const PRODUCT_ENABLE_LOADING = "PRODUCT_ENABLE_LOADING";

export const PRODUCT_ERROR = "PRODUCT_ERROR";