export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"

export const ALL_PRODUCTS_ENABLE_LOADING = "ALL_PRODUCTS_ENABLE_LOADING"

export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR"

export const CREATE_PRODUCT = "CREATE_PRODUCT"

export const PRODUCT_ENABLE_LOADING = "PRODUCT_ENABLE_LOADING"

export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR"