export const GET_ALL_SUB_CATEGORIES = "GET_ALL_SUB_CATEGORIES"

export const ALL_SUB_CATEGORIES_ENABLE_LOADING = "ALL_SUB_CATEGORIES_ENABLE_LOADING"

export const GET_ALL_SUB_CATEGORIES_ERROR = "GET_ALL_SUB_CATEGORIES_ERROR"

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"

export const SUB_CATEGORY_ENABLE_LOADING = "SUB_CATEGORY_ENABLE_LOADING"

export const CREATE_SUB_CATEGORY_ERROR = "CREATE_SUB_CATEGORY_ERROR"