export const GET_ALL_SUB_CATEGORIES = "GET_ALL_SUB_CATEGORIES";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";

export const SUB_CATEGORY_ENABLE_LOADING = "SUB_CATEGORY_ENABLE_LOADING";

export const SUB_CATEGORY_ERROR = "SUB_CATEGORY_ERROR";